/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/renderer/index.html",
    "./src/renderer/**/*.{svelte,js,ts}"
  ],
  theme: {
    extend: {
      colors: {
        "background": "var(--tw-color-background)",
        "primary-fixed": "var(--tw-color-primary-fixed)",
        "secondary": "var(--tw-color-secondary)",
        "surface-container-highest": "var(--tw-color-surface-container-highest)",
        "secondary-fixed": "var(--tw-color-secondary-fixed)",
        "on-secondary": "var(--tw-color-on-secondary)",
        "surface-dim": "var(--tw-color-surface-dim)",
        "on-secondary-fixed-variant": "var(--tw-color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--tw-color-tertiary-fixed)",
        "surface": "var(--tw-color-surface)",
        "on-secondary-container": "var(--tw-color-on-secondary-container)",
        "surface-container": "var(--tw-color-surface-container)",
        "tertiary-container": "var(--tw-color-tertiary-container)",
        "inverse-surface": "var(--tw-color-inverse-surface)",
        "primary": "var(--tw-color-primary)",
        "on-primary-fixed-variant": "var(--tw-color-on-primary-fixed-variant)",
        "on-tertiary-container": "var(--tw-color-on-tertiary-container)",
        "on-primary-fixed": "var(--tw-color-on-primary-fixed)",
        "error-container": "var(--tw-color-error-container)",
        "secondary-container": "var(--tw-color-secondary-container)",
        "surface-container-low": "var(--tw-color-surface-container-low)",
        "on-surface-variant": "var(--tw-color-on-surface-variant)",
        "tertiary": "var(--tw-color-tertiary)",
        "surface-bright": "var(--tw-color-surface-bright)",
        "on-secondary-fixed": "var(--tw-color-on-secondary-fixed)",
        "on-primary": "var(--tw-color-on-primary)",
        "on-surface": "var(--tw-color-on-surface)",
        "secondary-fixed-dim": "var(--tw-color-secondary-fixed-dim)",
        "primary-container": "var(--tw-color-primary-container)",
        "outline": "var(--tw-color-outline)",
        "on-background": "var(--tw-color-on-background)",
        "surface-variant": "var(--tw-color-surface-variant)",
        "outline-variant": "var(--tw-color-outline-variant)",
        "surface-container-lowest": "var(--tw-color-surface-container-lowest)",
        "on-tertiary-fixed-variant": "var(--tw-color-on-tertiary-fixed-variant)",
        "on-error-container": "var(--tw-color-on-error-container)",
        "on-tertiary-fixed": "var(--tw-color-on-tertiary-fixed)",
        "on-error": "var(--tw-color-on-error)",
        "primary-fixed-dim": "var(--tw-color-primary-fixed-dim)",
        "surface-tint": "var(--tw-color-surface-tint)",
        "surface-container-high": "var(--tw-color-surface-container-high)",
        "error": "var(--tw-color-error)",
        "tertiary-fixed-dim": "var(--tw-color-tertiary-fixed-dim)",
        "inverse-primary": "var(--tw-color-inverse-primary)",
        "on-tertiary": "var(--tw-color-on-tertiary)",
        "on-primary-container": "var(--tw-color-on-primary-container)",
        "inverse-on-surface": "var(--tw-color-inverse-on-surface)",
        "legacy-primary": "var(--tw-color-legacy-primary)",
        "legacy-secondary": "var(--tw-color-legacy-secondary)",
        "legacy-accent": "var(--tw-color-legacy-accent)",
        "legacy-surface": "var(--tw-color-legacy-surface)",
        "legacy-surface2": "var(--tw-color-legacy-surface2)",
        "legacy-border": "var(--tw-color-legacy-border)",
        "legacy-success": "var(--tw-color-legacy-success)",
        "legacy-warning": "var(--tw-color-legacy-warning)",
        "legacy-danger": "var(--tw-color-legacy-danger)",
      }, 
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "old-sm": "6px",
        "old-md": "10px",
        "old-lg": "16px",
        "old-xl": "24px",
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "lg": "24px",
        "sidebar_width": "260px",
        "xl": "32px",
        "max_content_width": "800px",
        "xs": "4px",
        "unit": "4px"
      },
      fontFamily: {
        "code": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "h1": ["Inter"],
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "display": ["Inter"],
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "code": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "h1": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h2": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      animation: {
        'fade-in':    'fadeIn 250ms ease forwards',
        'slide-up':   'slideUp 300ms cubic-bezier(0.4,0,0.2,1) forwards',
        'shimmer':    'shimmer 1.5s infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp:   { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        shimmer:   { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        pulseGlow: { '0%,100%': { boxShadow: '0 0 8px rgba(124,58,237,0.2)' }, '50%': { boxShadow: '0 0 24px rgba(124,58,237,0.5)' } },
      },
      backdropBlur: { glass: '16px' },
    },
  },
  plugins: [],
}
