/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/renderer/index.html",
    "./src/renderer/**/*.{svelte,js,ts}"
  ],
  theme: {
    extend: {
      colors: {
        "background": "#0b1326",
        "primary-fixed": "#d8e2ff",
        "secondary": "#b7c8e1",
        "surface-container-highest": "#2d3449",
        "secondary-fixed": "#d3e4fe",
        "on-secondary": "#213145",
        "surface-dim": "#0b1326",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed": "#ffdcc6",
        "surface": "#0b1326",
        "on-secondary-container": "#a9bad3",
        "surface-container": "#171f33",
        "tertiary-container": "#df7412",
        "inverse-surface": "#dae2fd",
        "primary": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-container": "#461f00",
        "on-primary-fixed": "#001a42",
        "error-container": "#93000a",
        "secondary-container": "#3a4a5f",
        "surface-container-low": "#131b2e",
        "on-surface-variant": "#c2c6d6",
        "tertiary": "#ffb786",
        "surface-bright": "#31394d",
        "on-secondary-fixed": "#0b1c30",
        "on-primary": "#002e6a",
        "on-surface": "#dae2fd",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-container": "#4d8eff",
        "outline": "#8c909f",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        "outline-variant": "#424754",
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed-variant": "#723600",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#311400",
        "on-error": "#690005",
        "primary-fixed-dim": "#adc6ff",
        "surface-tint": "#adc6ff",
        "surface-container-high": "#222a3d",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb786",
        "inverse-primary": "#005ac2",
        "on-tertiary": "#502400",
        "on-primary-container": "#00285d",
        "inverse-on-surface": "#283044",
        
        // Legacy colors to maintain backwards compatibility
        "legacy-primary":   '#7c3aed',
        "legacy-secondary": '#06b6d4',
        "legacy-accent":    '#7c3aed',
        "legacy-surface":   '#161b22',
        "legacy-surface2":  '#1c2330',
        "legacy-border":    '#30363d',
        "legacy-success":   '#10b981',
        "legacy-warning":   '#f59e0b',
        "legacy-danger":    '#ef4444',
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "old-sm": "6px",
        "old-md": "10px",
        "old-lg": "16px",
        "old-xl": "24px",
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "lg": "24px",
        "sidebar_width": "260px",
        "xl": "32px",
        "max_content_width": "800px",
        "xs": "4px",
        "unit": "4px"
      },
      fontFamily: {
        "code": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "h1": ["Inter"],
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "display": ["Inter"],
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "code": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "h1": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h2": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      animation: {
        'fade-in':    'fadeIn 250ms ease forwards',
        'slide-up':   'slideUp 300ms cubic-bezier(0.4,0,0.2,1) forwards',
        'shimmer':    'shimmer 1.5s infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp:   { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        shimmer:   { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        pulseGlow: { '0%,100%': { boxShadow: '0 0 8px rgba(124,58,237,0.2)' }, '50%': { boxShadow: '0 0 24px rgba(124,58,237,0.5)' } },
      },
      backdropBlur: { glass: '16px' },
    },
  },
  plugins: [],
}
